server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/jai
    username: gyunghoe
    password: gyunghoe

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 1000
#        show_sql: true
#        format_sql: true
